spring:
    profiles:
        active: dev
---
spring:
    profiles: dev  #开发环境
    application:
        name: microservicecloud1-config-dev
config:
    info:  version=5
---
spring:
    profiles: test  #测试环境
    application:
        name: microservicecloud1-config-test
config:
    info:  version=2
